// scripts/build-shaders.mjs
// Converts src/ui/shaders/source/*.frag|*.vert into src/ui/shaders/generated.ts
// so shaders can be imported as plain strings (no bundler loaders needed):
//   import { marbleHeroFrag, scanBeamFrag } from "@/ui/shaders/generated";
// Run: pnpm shaders:build   (add to package.json; also run in "predev" and "prebuild")

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

const SRC_DIR = "src/ui/shaders/source";
const OUT_FILE = "src/ui/shaders/generated.ts";

// "marble-hero.frag" → "marbleHeroFrag" ; "fullscreen.vert" → "fullscreenVert"
const toCamel = (name) => name.replace(/[-.](\w)/g, (_, c) => c.toUpperCase());

const files = readdirSync(SRC_DIR)
  .filter((f) => /\.(frag|vert)$/.test(f))
  .sort();

if (files.length === 0) {
  console.error(`[build-shaders] No shader files found in ${SRC_DIR}`);
  process.exit(1);
}

let out = "// AUTO-GENERATED by scripts/build-shaders.mjs — do not edit by hand.\n";
out += "// Source of truth: src/ui/shaders/source/*.frag|*.vert\n\n";

for (const file of files) {
  const code = readFileSync(join(SRC_DIR, file), "utf8");
  out += `export const ${toCamel(file)} = ${JSON.stringify(code)};\n\n`;
}

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out);
console.log(`[build-shaders] wrote ${OUT_FILE} (${files.length} shaders)`);
