/**
 * ICS Calendar Exporter for Action Checklists.
 * brain.md §7 P6, architecture.md §5.3
 */

import { createEvents, type EventAttributes, type DateArray } from "ics";
import type { ChecklistItem } from "@/core/domain/schemas";

/**
 * Parses a due date string or returns a sensible default DateArray [year, month, day, hour, minute].
 * Month is 1-indexed for `ics`.
 */
export function parseDueDateToDateArray(
  dueStr?: string,
  baseDate = new Date()
): DateArray {
  if (!dueStr || !dueStr.trim()) {
    // Default: 7 days from baseDate at 09:00
    const target = new Date(baseDate.getTime() + 7 * 24 * 60 * 60 * 1000);
    return [
      target.getFullYear(),
      target.getMonth() + 1,
      target.getDate(),
      9,
      0,
    ];
  }

  const s = dueStr.trim().toLowerCase();

  // Pattern 1: ISO YYYY-MM-DD
  const isoMatch = s.match(/(\d{4})-(\d{2})-(\d{2})/);
  if (isoMatch && isoMatch[1] && isoMatch[2] && isoMatch[3]) {
    const y = parseInt(isoMatch[1], 10);
    const m = parseInt(isoMatch[2], 10);
    const d = parseInt(isoMatch[3], 10);
    return [y, m, d, 9, 0];
  }

  // Pattern 2: "within X days" or "in X days"
  const daysMatch = s.match(/(?:within|in)\s+(\d+)\s+days?/);
  if (daysMatch && daysMatch[1]) {
    const days = parseInt(daysMatch[1], 10);
    const target = new Date(baseDate.getTime() + days * 24 * 60 * 60 * 1000);
    return [
      target.getFullYear(),
      target.getMonth() + 1,
      target.getDate(),
      9,
      0,
    ];
  }

  // Pattern 3: "within X months" or "in X months"
  const monthsMatch = s.match(/(?:within|in)\s+(\d+)\s+months?/);
  if (monthsMatch && monthsMatch[1]) {
    const months = parseInt(monthsMatch[1], 10);
    const target = new Date(baseDate);
    target.setMonth(target.getMonth() + months);
    return [
      target.getFullYear(),
      target.getMonth() + 1,
      target.getDate(),
      9,
      0,
    ];
  }

  // Pattern 4: "by the X(st|nd|rd|th)" (e.g. 1st of each month) -> next occurrence
  const dayOfMonthMatch = s.match(/by\s+the\s+(\d+)(?:st|nd|rd|th)?/);
  if (dayOfMonthMatch && dayOfMonthMatch[1]) {
    const day = Math.min(28, Math.max(1, parseInt(dayOfMonthMatch[1], 10)));
    const target = new Date(baseDate);
    if (target.getDate() >= day) {
      target.setMonth(target.getMonth() + 1);
    }
    target.setDate(day);
    return [
      target.getFullYear(),
      target.getMonth() + 1,
      target.getDate(),
      9,
      0,
    ];
  }

  // Default fallback: 14 days from baseDate
  const target = new Date(baseDate.getTime() + 14 * 24 * 60 * 60 * 1000);
  return [
    target.getFullYear(),
    target.getMonth() + 1,
    target.getDate(),
    9,
    0,
  ];
}

/**
 * Builds standard ICS calendar text from an array of checklist items.
 */
export function buildChecklistICS(
  items: ChecklistItem[],
  documentTitle = "Document"
): Promise<string> {
  return new Promise((resolve, reject) => {
    if (items.length === 0) {
      resolve("");
      return;
    }

    const events: EventAttributes[] = items.map((item, idx) => {
      const start = parseDueDateToDateArray(item.due, new Date(Date.now() + idx * 3600000));
      const descriptionLines: string[] = [
        `Obligation / Task: ${item.item}`,
        `Owner: ${item.owner === "you" ? "You" : item.owner === "other_party" ? "Other Party" : "Both Parties"}`,
        `Priority: ${item.priority.toUpperCase()}`,
      ];

      if (item.due) {
        descriptionLines.push(`Stated Timeline: ${item.due}`);
      }

      if (item.citation) {
        descriptionLines.push(
          `Document Citation [${item.citation.clauseId}]: "${item.citation.quote}"`
        );
      }

      descriptionLines.push(
        `\nDocument: ${documentTitle}`,
        "Generated by LexLens — Legal Document Intelligence"
      );

      return {
        title: `[LexLens] ${item.item.slice(0, 80)}`,
        description: descriptionLines.join("\n"),
        start,
        duration: { hours: 1, minutes: 0 },
        categories: ["Legal", "Contract", item.priority],
        status: "CONFIRMED",
      };
    });

    createEvents(events, (error, value) => {
      if (error) {
        reject(error);
        return;
      }
      resolve(value ?? "");
    });
  });
}

/**
 * Triggers browser download of generated .ics calendar file.
 */
export function triggerICSDownload(
  icsContent: string,
  filename = "legal-obligations.ics"
): void {
  if (typeof window === "undefined" || !icsContent) return;

  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", filename.endsWith(".ics") ? filename : `${filename}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
